### ISSUE TITLE
Cannot read property 'semanticType' of undefined

### ISSUE THREAD

**Issue by petermr** [ContentMine/getpapers#104]
```
(py35)localhost:phyto pm286$ getpapers -q eugenol -o eugenol -x -k 100 --minedterms
```
gives
```
Downloading files [=====================] 100% (100/100) [2.3s elapsed, eta 0.0]
info: All downloads succeeded!
info: Writing mined term summary CSV files to minedterms_summary/

/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:528
    terms.semanticTypeList.semanticType.forEach(function(termset) {
                          ^
TypeError: Cannot read property 'semanticType' of undefined
    at /Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:528:27
    at Array.forEach (native)
    at EuPmc.summariseMinedTerms (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:525:40)
    at EuPmc.nextDlTask (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:232:5)
    at donefunc (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/download.js:86:5)
    at /Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/lodash/index.js:7305:23
    at Object.oncomplete (fs.js:108:15)

```

**Comment by blahah** [comment]
this appears to be a result of my being slapdash when implementing the new `--minedterms` functionality. I'll update with explicit checking tomorrow.
