### ISSUE TITLE
Name Too Long crash (ENAMETOOLONG)

### ISSUE THREAD

**Issue by petermr** [ContentMine/getpapers#108]
```

Error: ENAMETOOLONG, name too long '/Users/pm286/workspace/cmdev/norma-dev/epmc/puccinia/The influence of fungal biotrophy on low temperature responses in winter cereals : a study, under acclimating and non-acclimating conditions, on the accumulation of transcripts from selected barley low-temperature-responsive (blt) genes, and on freezing susceptibility, following inoculation of winter barley (cv. Igri) with either powdery mildew (Erysiphe graminis f.sp. hordei) or leaf rust (Puccinia hordei).'
    at Object.fs.mkdirSync (fs.js:654:18)
    at Function.sync (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/mkdirp/index.js:71:13)
    at EuPmc.writeRecord (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:556:10)
    at /Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:169:11
    at Array.forEach (native)
    at EuPmc.handleSearchResults (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:168:20)
    at EuPmc.completeCallback (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:113:11)
    at Request.emit (events.js:98:17)
    at Request.mixin._fireSuccess (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:229:10)
    at /Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:161:20
localhost:epmc pm286$ getpapers -version

  error: unknown option `-v'

localhost:epmc pm286$ getpapers --version
0.4.5
```
This comes from a query returning 3470 hits ("Puccinia")

**Comment by blahah** [comment]
@petermr did getpapers try to create that directory? Or was it already made?

**Comment by tarrow** [comment]
getpapers tried to make it; I'm trying to replicate it now

**Comment by tarrow** [comment]
So the issue is that the cammand was with '-a'. This means EuropePMC returns things that are not in the PMC dataset. i.e. somethings that only have the title, or doi as their identifier. The directory we make is this identifier. It used to be that nothing bad would happen because we would only make a directory of things with a PMCid (if you passed -x or -p). Now we make a directory for everything unless you pass a '-n' because we now split up the metadata and put a little blob in each directory.
