### ISSUE TITLE
contentmine installation

### ISSUE THREAD

**Issue by alexmaina** [ContentMine/getpapers#125]
I have freshly installed contentmine in my Ubuntu 14.04 box. However when i run this test command

getpapers -q 'malaria' -n -o malaria

i get the following error

/usr/local/lib/node_modules/getpapers/lib/eupmc.js:44
        fs.readFile('eupmc_results.json', (err,data) => {
                                                      ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/getpapers/lib/api.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

What might i be doing/have done wrong?

**Comment by larsgw** [comment]
It seems your version of Node.js doesn't support arrow functions (the `(err,data) => {` bit). Node suppports arrow function since v4.3.2, and since v0.12.16 if you include the `--harmony` flag. See http://node.green/. I get the same error for Node v0.10.29. This is a problem with the source code, not the command.

**Comment by larsgw** [comment]
I was going to fix it, but apparently the code uses other features not available for v0.10.29 (and maybe higher), like `for...of`.
