### ISSUE TITLE
Potentially unhandled rejection - Error: read ECONNRESET

### ISSUE THREAD

**Issue by sedimentation-fault** [ContentMine/getpapers#155]
At 7% of downloading all 24818 papers of the math.DG category of _arxiv.org_ with:

`getpapers --api 'arxiv' --query 'cat:math.DG' --outdir arxiv/math.DG -p`

I got:

```
Potentially unhandled rejection [2] Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
Potentially unhandled rejection [4] Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
Potentially unhandled rejection [6] Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
Potentially unhandled rejection [8] Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
Potentially unhandled rejection [10] Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
```

The same error occurs after rerunning the same command as above,
only at a different place (4% (1019/24818))...and it happens again and again, always at different places.

## Reason
It seems that the ubiquitous 

> Connection reset by peer

error is left unhandled by _getpapers_. This is a too common (I would almost say _normal_) error to be thrown unhandled at the user. 

## Solution
Do something, maybe along the lines of 
https://github.com/Vexera/retry-stream/blob/master/index.js

**Comment by sedimentation-fault** [comment]
To go past this error, one may try to execute _curl_ (or a wrapper to _curl_ that handles HTTP errors gracefully) directly, as shown in my **workaround** at https://github.com/ContentMine/getpapers/issues/152.

It works: you _will_ go past this error - [only to encounter a plethora of new ones](https://github.com/ContentMine/getpapers/issues/156)...

**Comment by tarrow** [comment]
I'll have a look and see if I can replicate this.

Is this occurring during the metadata or pdf download stage? To be honest little work has been done recently on arxiv (due to lack of interest) but I'd be keen to make it work nicely for you. 

Slightly cleaner error handling would be nice; unfortunately in the end "connection reset by peer" is the best we can do though. (but without a stack trace and after having retried a few times)

In the past I've found you might want to check your wireless card isn't falling asleep. Alternatively if you're using our virtual machine image there seems to be a bug in the virtualbox drivers on some platforms that causes this.

**Comment by sedimentation-fault** [comment]
This occurs during pdf download. No wifi or virtual images in use here.

Connection reset is quite a common error. Start hammering any web server and, after a few hundred "200 OK"'s, I bet you'll get a "connection reset by peer" error. _arxiv_ even seems to be quite robust in doing so only after the first _thousand_ downloads...

You should be able to replicate the error by using my example with the math.DG category and its 24000+ papers.

Note that this error prevents me from going past the first 1000-1500 papers. The 

`if (err) throw err;`

line in the  _downloadURL_ function of _download.js_ causes _getpapers_ to stop as soon as it encounters it. Retrying is futile.
