### ISSUE TITLE
eupmc: -a AND -x fails

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/getpapers#32]
Either switch on their own is fine but trying to do -a AND -x crashes it.
Expected behaviour: search all (not just OA), and download full text XML of the OA ones.

```
$ getpapers -q 'Gasteria' --api eupmc -a -x   -l verbose  --outdir ./zar
info: Searching using eupmc API
debug: http://www.ebi.ac.uk/europepmc/webservices/rest/search/query=Gasteria&resulttype=core
info: Found 61 results
Retrieving results [============------------------] 41% (eta 0.0s)debug: http://www.ebi.ac.uk/europepmc/webservices/rest/search/query=Gasteria&resulttype=core&page=1
Retrieving results [=========================-----] 82% (eta 0.1s)debug: http://www.ebi.ac.uk/europepmc/webservices/rest/search/query=Gasteria&resulttype=core&page=2
Retrieving results [==============================] 100% (eta 0.0s)
info: Done collecting results
info: Duplicate records found: 50 unique results identified
info: Saving result metdata
info: Full EUPMC result metadata written to eupmc_results.json
info: Extracting fulltext HTML URL list (may not be available for all articles)
warn: Article with pmcid "PMC3978243" had no fulltext HTML url
warn: Article with pmcid "PMC3690993" had no fulltext HTML url
warn: Article with pmcid "PMC3605904" had no fulltext HTML url
warn: Article with pmcid "PMC3371435" had no fulltext HTML url
warn: Article with pmcid "PMC3364152" had no fulltext HTML url
warn: Article with pmcid "PMC3286288" had no fulltext HTML url
warn: Article with pmcid "PMC3066391" had no fulltext HTML url
warn: Article with pmcid "PMC3043933" had no fulltext HTML url
warn: Article with pmcid "PMC3002468" had no fulltext HTML url
warn: Article with pmcid "PMC4242389" had no fulltext HTML url
warn: Article with pmcid "PMC4233834" had no fulltext HTML url
warn: Article with pmcid "PMC2871514" had no fulltext HTML url
warn: Article with pmcid "PMC1460952" had no fulltext HTML url
warn: Article with pmcid "PMC2602195" had no fulltext HTML url
warn: Article with pmcid "PMC1693204" had no fulltext HTML url
warn: Article with pmcid "PMC1203420" had no fulltext HTML url
warn: Article with pmcid "PMC1208741" had no fulltext HTML url
warn: Article with pmcid "PMC1209182" had no fulltext HTML url
warn: Article with pmcid "PMC1208723" had no fulltext HTML url
info: Fulltext HTML URL list written to fulltext_html_urls.txt
warn: Article with title "Gasteria plant named 'WT10' did not have a PMCID (therefore no XML)
warn: Article with pmid "8835456 did not have a PMCID (therefore no XML)
warn: Article with pmid "9087376 did not have a PMCID (therefore no XML)
warn: Article with pmid "24240951 did not have a PMCID (therefore no XML)
warn: Article with pmid "18775771 did not have a PMCID (therefore no XML)
warn: Article with pmid "13033248 did not have a PMCID (therefore no XML)
warn: Article with pmid "5594485 did not have a PMCID (therefore no XML)
warn: Article with pmid "18098797 did not have a PMCID (therefore no XML)
info: Downloading fulltext XML files
debug: Creating directory: PMC4377467/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC4377467/fullTextXML
debug: Creating directory: PMC4202640/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC4202640/fullTextXML
debug: Creating directory: PMC4202400/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC4202400/fullTextXML
debug: Creating directory: PMC3978243/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3978243/fullTextXML
debug: Creating directory: PMC4152747/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC4152747/fullTextXML
debug: Creating directory: PMC3690993/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3690993/fullTextXML
debug: Creating directory: PMC3729011/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3729011/fullTextXML
debug: Creating directory: PMC3605904/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3605904/fullTextXML
debug: Creating directory: PMC3371435/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3371435/fullTextXML
debug: Creating directory: PMC3364152/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3364152/fullTextXML
debug: Creating directory: PMC3305877/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3305877/fullTextXML
debug: Creating directory: PMC3286288/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3286288/fullTextXML
debug: Creating directory: Gasteria plant named 'WT10'/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3066391/fullTextXML
debug: Creating directory: PMC3066391/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3043933/fullTextXML
debug: Creating directory: PMC3043933/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC3002468/fullTextXML
debug: Creating directory: PMC3002468/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC2141413/fullTextXML
debug: Creating directory: 8835456/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC4242389/fullTextXML
debug: Creating directory: 9087376/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC4233834/fullTextXML
debug: Creating directory: 24240951/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC4257511/fullTextXML
debug: Creating directory: 18775771/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC2871514/fullTextXML
debug: Creating directory: 13033248/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1460952/fullTextXML
debug: Creating directory: PMC2141413/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC4243674/fullTextXML
debug: Creating directory: PMC4242389/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC2602195/fullTextXML
debug: Creating directory: PMC4233834/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1462085/fullTextXML
debug: Creating directory: PMC4257511/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1693204/fullTextXML
debug: Creating directory: PMC2871514/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC2707325/fullTextXML
debug: Creating directory: PMC1460952/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC2844068/fullTextXML
debug: Creating directory: PMC4243674/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC2707867/fullTextXML
debug: Creating directory: PMC2602195/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1203420/fullTextXML
debug: Creating directory: PMC1462085/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC2803647/fullTextXML
debug: Creating directory: PMC1693204/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1078655/fullTextXML
debug: Creating directory: PMC2707325/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1076571/fullTextXML
debug: Creating directory: 5594485/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1077958/fullTextXML
debug: Creating directory: 18098797/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1209227/fullTextXML
debug: Creating directory: PMC2844068/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1076789/fullTextXML
debug: Creating directory: PMC2707867/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1208741/fullTextXML
debug: Creating directory: PMC1203420/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1076941/fullTextXML
debug: Creating directory: PMC2803647/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1209172/fullTextXML
debug: Creating directory: PMC1078655/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC438925/fullTextXML
debug: Creating directory: PMC1076571/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1209182/fullTextXML
debug: Creating directory: PMC1077958/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1200927/fullTextXML
debug: Creating directory: PMC1209227/
debug: Downloading XML: http://www.ebi.ac.uk/europepmc/webservices/rest/PMC1208723/fullTextXML
Downloading files [=-----------------------------] 2% (eta 0.0s)
/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:333
          fourohfour();
          ^
TypeError: undefined is not a function
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:333:11
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/index.js:152:6
    at BufferStream.<anonymous> (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/node_modules/read-all-stream/index.js:52:3)
    at BufferStream.emit (events.js:117:20)
    at finishMaybe (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:499:14)
    at endWritable (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:509:3)
    at BufferStream.Writable.end (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:474:5)
    at IncomingMessage.onend (_stream_readable.js:502:10)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
```

**Comment by Blahah** [comment]
The behaviour you expected is what it is trying to do, but there is a problem with the `fourohfour` function.

**Comment by Blahah** [comment]
Actually I was wrong - in addition to the problem with the `fourohfour` function, it was trying to download XML for articles that are 'free' but not 'open access' in EPMC! Both problems now resolved, and fixes will be in the next release.
