### ISSUE TITLE
ieee -a fails when search hits == 0

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/getpapers#34]
I saw the no XML warning for using ieee with -x (XML) but there's no similar warning here:

```
getpapers -q 'Gasteria' --api ieee -a  --outdir ./car
info: Searching using ieee API

TypeError: Cannot read property 'totalfound' of undefined
    at IEEE.completeCallback (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/lib/ieee.js:72:38)
    at Request.emit (events.js:98:17)
    at Request.mixin._fireSuccess (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:226:10)
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:158:20
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:448:9
    at Parser.<anonymous> (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/lib/xml2js.js:344:20)
    at Parser.emit (events.js:95:17)
    at Object.saxParser.onclosetag (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/lib/xml2js.js:314:24)
    at emit (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
```

**Comment by Blahah** [comment]
`-a` should work with IEEE

**Comment by rossmounce** [comment]
It's because there are 0 results for that particular search.

You're right that in the general case ieee -a works e.g.
```
$getpapers -q 'john jane hamburg' --api ieee -a  --outdir ./car
```

BUT for a search string that has zero hits it fails:
```
getpapers -q 'ZEROHITSEARCH' --api ieee -a  --outdir ./car
info: Searching using ieee API

TypeError: Cannot read property 'totalfound' of undefined
    at IEEE.completeCallback (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/lib/ieee.js:72:38)
    at Request.emit (events.js:98:17)
    at Request.mixin._fireSuccess (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:226:10)
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:158:20
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:449:9
    at Parser.<anonymous> (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/lib/xml2js.js:344:20)
    at Parser.emit (events.js:95:17)
    at Object.saxParser.onclosetag (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/lib/xml2js.js:314:24)
    at emit (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
```

**Comment by Blahah** [comment]
Note that this problem was unrelated to `-a` - any time zero results were found this crash would happen, regardless of whether `-a` was set.
