### ISSUE TITLE
404 for single open Elsevier PDF because it doesn't exist?

### ISSUE THREAD

**Issue by rossmounce** [ContentMine/getpapers#48]
404 error when trying to get PDF of this one open article from the journal _Academic Radiology_:

I suspect it's because there is no PDF for this article at EuropePMC: http://europepmc.org/articles/PMC4234081 . Does `getpapers` just assume there's PDF if there's XML available?

```
getpapers --query 'Journal:"Academic Radiology" AND FIRST_PDATE:[2010-01-01 TO 2015-07-01]' -p  --outdir elseacrad
info: Searching using eupmc API
info: Found 1 open access results
Retrieving results [==============================] 100% (eta 0.0s)
info: Done collecting results
info: Saving result metdata
info: Full EUPMC result metadata written to eupmc_results.json
info: Extracting fulltext HTML URL list (may not be available for all articles)
warn: Article with pmcid "PMC4234081" had no fulltext HTML url
info: Downloading fulltext PDF files
Downloading files [==============================] 100% (eta 0.0s)

/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:333
          fourohfour();
          ^
TypeError: undefined is not a function
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:333:11
    at /home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/index.js:152:6
    at BufferStream.<anonymous> (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/node_modules/read-all-stream/index.js:52:3)
    at BufferStream.emit (events.js:117:20)
    at finishMaybe (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:499:14)
    at afterWrite (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at afterTick (/home/ross/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/got/node_modules/read-all-stream/node_modules/readable-stream/node_modules/process-nextick-args/index.js:11:8)
    at process._tickCallback (node.js:448:13)
```

Downloading the XML for the same article is fine, no problem
```
getpapers --query 'Journal:"Academic Radiology" AND FIRST_PDATE:[2010-01-01 TO 2015-07-01]' -x  --outdir elseacrad
info: Searching using eupmc API
info: Found 1 open access results
Retrieving results [==============================] 100% (eta 0.0s)
info: Done collecting results
info: Saving result metdata
info: Full EUPMC result metadata written to eupmc_results.json
info: Extracting fulltext HTML URL list (may not be available for all articles)
warn: Article with pmcid "PMC4234081" had no fulltext HTML url
info: Downloading fulltext XML files
Downloading files [==============================] 100% (eta 0.0s)
info: All XML downloads succeeded!
```

**Comment by Blahah** [comment]
Yeah, for some reason that PDF is not available. This is not a bug with getpapers, so should be reported upstream to europePMC.

```
    "fullTextUrlList": [
      {
        "fullTextUrl": [
          {
            "availability": [
              "Open access"
            ],
            "availabilityCode": [
              "OA"
            ],
            "documentStyle": [
              "pdf"
            ],
            "site": [
              "Europe_PMC"
            ],
            "url": [
              "http://europepmc.org/articles/PMC4234081?pdf=render"
            ]
          },
          {
            "availability": [
              "Open access"
            ],
            "availabilityCode": [
              "OA"
            ],
            "documentStyle": [
              "html"
            ],
            "site": [
              "Europe_PMC"
            ],
            "url": [
              "http://europepmc.org/articles/PMC4234081"
            ]
          },
          {
            "availability": [
              "Subscription required"
            ],
            "availabilityCode": [
              "S"
            ],
            "documentStyle": [
              "doi"
            ],
            "site": [
              "DOI"
            ],
            "url": [
              "http://dx.doi.org/10.1016/j.acra.2014.06.014"
            ]
          }
        ]
      }
    ],
```

The PDF url gives me 'Server Error' in a browser.
