### ISSUE TITLE
Ticker Breaking

### ISSUE THREAD

**Issue by daMogli** [ContentMine/getpapers#59]
Seems like the ticker is breaking?

```
getpapers(master)$ getpapers --query "cat: Quantative Biology" --api arxiv --outdir ~/test
info: Searching using arxiv API
info: Found 5056 results
Retrieving results [===============---------------] 49% (eta 145.8s)/usr/local/lib/node_modules/getpapers/lib/arxiv.js:87
  arxiv.pageprogress.tick(result.length);
                                ^
TypeError: Cannot read property 'length' of undefined
    at ArXiv.completeCallback (/usr/local/lib/node_modules/getpapers/lib/arxiv.js:87:33)
    at Request.emit (events.js:110:17)
    at Request.mixin._fireSuccess (/usr/local/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:229:10)
    at /usr/local/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:161:20
    at /usr/local/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:456:9
    at Parser.<anonymous> (/usr/local/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/lib/xml2js.js:344:20)
    at Parser.emit (events.js:107:17)
    at Object.saxParser.onclosetag (/usr/local/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/lib/xml2js.js:314:24)
    at emit (/usr/local/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/usr/local/lib/node_modules/getpapers/node_modules/restler/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
```

**Comment by Blahah** [comment]
The problem is that there are 0 entries in the data that come back from the arxiv API, and we aren't handling that error well. Thanks for the report, will fix asap.
