### ISSUE TITLE
Cannot read property 'hitCount' of undefined

### ISSUE THREAD

**Issue by petermr** [ContentMine/getpapers#73]
running getpapers

```
localhost:clintrial pm286$ getpapers -q "trialsjournal.com AND PUB_YEAR:2014" -o clintrial  
info: Searching using eupmc API

TypeError: Cannot read property 'hitCount' of undefined
    at EuPmc.completeCallback (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/lib/eupmc.js:63:35)
    at Request.emit (events.js:98:17)
    at Request.mixin._fireError (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:207:10)
    at ClientRequest.<anonymous> (/Users/pm286/.nvm/v0.10.38/lib/node_modules/getpapers/node_modules/restler/lib/restler.js:246:14)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1548:9)
    at Socket.emit (events.js:95:17)
    at net.js:834:16
    at process._tickCallback (node.js:448:13)
localhost:clintrial pm286$ 
```

**Comment by tarrow** [comment]
I'm unable to replicate this. I just get back: 0 open access results.

I guess this might be caused by a badly formatted or non JSON blob coming back. Were you on a public WiFi network that does something nasty like injecting a sign up/log in page when this happened?

Can you still replicate the bug?

**Comment by tarrow** [comment]
To clarify we should still test the key before trying to access it.

**Comment by petermr** [comment]
In my experience anything that can be null / undefined will, at some stage, be null / undefined!! Crashes often terminate the process, whereas some are pathological entries (e.g. null content, invalid XML ...) and simply need skipping . So a message like:
```
skipped missing hitCount (probably feature of timeout)
```

**Comment by tarrow** [comment]
Sadly it means that the response from EuropePMC was bad so we really need to start the process again. I.e. it should probably 'die' but not crash just exit with code > 0.
